spring.application.name=ms-citas

# Puerto del servidor (distinto al de ms-ordenes)
server.port=8081

# Configuración Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=S2_FULLSTACK
spring.datasource.password=sumativa2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
